<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TemplateCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // ─── Invoice Templates ─────────────────────────────────────
            [
                'code' => 'invoice-default',
                'name' => 'Standard',
                'slug' => 'invoice-standard',
                'document_type' => 'invoice',
                'category' => 'general',
                'description' => 'Modèle de facture par défaut, propre et professionnel.',
                'view_path' => 'pdf.invoice',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'build/img/invoice/general-invoice-01.svg',
            ],
            [
                'code' => 'invoice-modern',
                'name' => 'Moderne',
                'slug' => 'invoice-moderne',
                'document_type' => 'invoice',
                'category' => 'general',
                'description' => 'Design moderne avec en-tête coloré et mise en page contemporaine.',
                'view_path' => 'pdf.templates.modern.invoice',
                'price' => 0,
                'is_free' => true,
                'is_featured' => false,
                'sort_order' => 2,
                'preview_image' => 'build/img/invoice/general-invoice-02.svg',
            ],
            [
                'code' => 'invoice-classic',
                'name' => 'Classique',
                'slug' => 'invoice-classique',
                'document_type' => 'invoice',
                'category' => 'general',
                'description' => 'Style classique avec bordures et structure traditionnelle.',
                'view_path' => 'pdf.templates.classic.invoice',
                'price' => 99,
                'is_free' => false,
                'is_featured' => false,
                'sort_order' => 3,
                'preview_image' => 'build/img/invoice/general-invoice-03.svg',
            ],
            [
                'code' => 'invoice-elegant',
                'name' => 'Élégant',
                'slug' => 'invoice-elegant',
                'document_type' => 'invoice',
                'category' => 'general',
                'description' => 'Design élégant avec dégradés et typographie raffinée.',
                'view_path' => 'pdf.templates.elegant.invoice',
                'price' => 99,
                'is_free' => false,
                'is_featured' => false,
                'sort_order' => 4,
                'preview_image' => 'build/img/invoice/general-invoice-04.svg',
            ],

            // ─── Quote Templates ───────────────────────────────────────
            [
                'code' => 'quote-default',
                'name' => 'Standard',
                'slug' => 'quote-standard',
                'document_type' => 'quote',
                'category' => 'general',
                'description' => 'Modèle de devis par défaut.',
                'view_path' => 'pdf.quote',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'build/img/invoice/general-invoice-05.svg',
            ],
            [
                'code' => 'quote-modern',
                'name' => 'Moderne',
                'slug' => 'quote-moderne',
                'document_type' => 'quote',
                'category' => 'general',
                'description' => 'Devis au design moderne.',
                'view_path' => 'pdf.templates.modern.quote',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 2,
                'preview_image' => 'build/img/invoice/general-invoice-06.svg',
            ],
            [
                'code' => 'quote-classic',
                'name' => 'Classique',
                'slug' => 'quote-classique',
                'document_type' => 'quote',
                'category' => 'general',
                'description' => 'Devis au style classique.',
                'view_path' => 'pdf.templates.classic.quote',
                'price' => 99,
                'is_free' => false,
                'sort_order' => 3,
                'preview_image' => 'build/img/invoice/general-invoice-07.svg',
            ],
            [
                'code' => 'quote-elegant',
                'name' => 'Élégant',
                'slug' => 'quote-elegant',
                'document_type' => 'quote',
                'category' => 'general',
                'description' => 'Devis au design élégant.',
                'view_path' => 'pdf.templates.elegant.quote',
                'price' => 99,
                'is_free' => false,
                'sort_order' => 4,
                'preview_image' => 'build/img/invoice/general-invoice-08.svg',
            ],

            // ─── Credit Note Templates ─────────────────────────────────
            [
                'code' => 'credit-note-default',
                'name' => 'Standard',
                'slug' => 'credit-note-standard',
                'document_type' => 'credit_note',
                'category' => 'general',
                'description' => "Modèle d'avoir par défaut.",
                'view_path' => 'pdf.credit-note',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'build/img/invoice/general-invoice-09.svg',
            ],
            [
                'code' => 'credit-note-modern',
                'name' => 'Moderne',
                'slug' => 'credit-note-moderne',
                'document_type' => 'credit_note',
                'category' => 'general',
                'description' => 'Avoir au design moderne.',
                'view_path' => 'pdf.templates.modern.credit-note',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 2,
                'preview_image' => 'build/img/invoice/general-invoice-10.svg',
            ],
            [
                'code' => 'credit-note-classic',
                'name' => 'Classique',
                'slug' => 'credit-note-classique',
                'document_type' => 'credit_note',
                'category' => 'general',
                'description' => 'Avoir au style classique.',
                'view_path' => 'pdf.templates.classic.credit-note',
                'price' => 99,
                'is_free' => false,
                'sort_order' => 3,
                'preview_image' => 'build/img/invoice/general-invoice-11.svg',
            ],
            [
                'code' => 'credit-note-elegant',
                'name' => 'Élégant',
                'slug' => 'credit-note-elegant',
                'document_type' => 'credit_note',
                'category' => 'general',
                'description' => 'Avoir au design élégant.',
                'view_path' => 'pdf.templates.elegant.credit-note',
                'price' => 99,
                'is_free' => false,
                'sort_order' => 4,
                'preview_image' => 'build/img/invoice/general-invoice-12.svg',
            ],

            // ─── Delivery Challan Templates ────────────────────────────
            [
                'code' => 'delivery-challan-default',
                'name' => 'Standard',
                'slug' => 'delivery-challan-standard',
                'document_type' => 'delivery_challan',
                'category' => 'general',
                'description' => 'Modèle de bon de livraison par défaut.',
                'view_path' => 'pdf.delivery-challan',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'build/img/invoice/general-invoice-13.svg',
            ],
            [
                'code' => 'delivery-challan-modern',
                'name' => 'Moderne',
                'slug' => 'delivery-challan-moderne',
                'document_type' => 'delivery_challan',
                'category' => 'general',
                'description' => 'Bon de livraison au design moderne.',
                'view_path' => 'pdf.templates.modern.delivery-challan',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 2,
                'preview_image' => 'build/img/invoice/general-invoice-14.svg',
            ],
            [
                'code' => 'delivery-challan-classic',
                'name' => 'Classique',
                'slug' => 'delivery-challan-classique',
                'document_type' => 'delivery_challan',
                'category' => 'general',
                'description' => 'Bon de livraison au style classique.',
                'view_path' => 'pdf.templates.classic.delivery-challan',
                'price' => 99,
                'is_free' => false,
                'sort_order' => 3,
                'preview_image' => 'build/img/invoice/general-invoice-15.svg',
            ],
            [
                'code' => 'delivery-challan-elegant',
                'name' => 'Élégant',
                'slug' => 'delivery-challan-elegant',
                'document_type' => 'delivery_challan',
                'category' => 'general',
                'description' => 'Bon de livraison au design élégant.',
                'view_path' => 'pdf.templates.elegant.delivery-challan',
                'price' => 99,
                'is_free' => false,
                'sort_order' => 4,
                'preview_image' => 'build/img/invoice/general-invoice-16.svg',
            ],

            // ─── Purchase Order Templates ──────────────────────────────
            [
                'code' => 'purchase-order-default',
                'name' => 'Standard',
                'slug' => 'purchase-order-standard',
                'document_type' => 'purchase_order',
                'category' => 'general',
                'description' => 'Modèle de bon de commande par défaut.',
                'view_path' => 'pdf.purchase-order',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'build/img/invoice/general-invoice-17.svg',
            ],
            [
                'code' => 'purchase-order-modern',
                'name' => 'Moderne',
                'slug' => 'purchase-order-moderne',
                'document_type' => 'purchase_order',
                'category' => 'general',
                'description' => 'Bon de commande au design moderne.',
                'view_path' => 'pdf.templates.modern.purchase-order',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 2,
                'preview_image' => 'build/img/invoice/general-invoice-18.svg',
            ],
            [
                'code' => 'purchase-order-classic',
                'name' => 'Classique',
                'slug' => 'purchase-order-classique',
                'document_type' => 'purchase_order',
                'category' => 'general',
                'description' => 'Bon de commande au style classique.',
                'view_path' => 'pdf.templates.classic.purchase-order',
                'price' => 99,
                'is_free' => false,
                'sort_order' => 3,
                'preview_image' => 'build/img/invoice/general-invoice-19.svg',
            ],
            [
                'code' => 'purchase-order-elegant',
                'name' => 'Élégant',
                'slug' => 'purchase-order-elegant',
                'document_type' => 'purchase_order',
                'category' => 'general',
                'description' => 'Bon de commande au design élégant.',
                'view_path' => 'pdf.templates.elegant.purchase-order',
                'price' => 99,
                'is_free' => false,
                'sort_order' => 4,
                'preview_image' => 'build/img/invoice/general-invoice-20.svg',
            ],
        ];

        foreach ($templates as $tpl) {
            DB::table('template_catalog')->updateOrInsert(
                ['code' => $tpl['code']],
                array_merge($tpl, [
                    'id' => DB::table('template_catalog')->where('code', $tpl['code'])->value('id') ?? Str::uuid()->toString(),
                    'engine' => 'blade',
                    'currency' => 'MAD',
                    'version' => '1.0.0',
                    'is_active' => true,
                    'is_featured' => $tpl['is_featured'] ?? false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
